# Generated by Django 4.0.4 on 2022-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64)),
                ('photo', models.ImageField(default=None, upload_to='')),
                ('address', models.CharField(default=None, max_length=120)),
                ('description', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
