# Generated by Django 4.0.4 on 2022-05-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('subtitle', models.CharField(max_length=250)),
                ('price', models.IntegerField(verbose_name='Ценевой сегмент')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
