# Generated by Django 4.0.4 on 2022-05-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
