# Generated by Django 4.0.4 on 2022-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категории')),
            ],
        ),
    ]
